<a href="https://colab.research.google.com/github/Norian05/StrukturData_D/blob/main/Latihan_Array_2D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matriks 3x3 dengan tampilan elemen tengahnya

In [5]:
import numpy as np
print("Matriks 3x3 dan tampilkan elemen tengah:")
m = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(m)
print("Elemen tengah:", m[1,1])

print("\nHitung jumlah seluruh matriks:")
elemen = np.sum(m)
print("Jumlah elemen:", elemen)

print("\nTabel nilai 3 mahasiswa x 4 mata kuliah:")
nm = np.array([[98, 88, 78, 90],
               [80, 88, 72, 78],
               [90, 92, 88, 86]])
print(nm)

Matriks 3x3 dan tampilkan elemen tengah:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Elemen tengah: 5

Hitung jumlah seluruh matriks:
Jumlah elemen: 45

Tabel nilai 3 mahasiswa x 4 mata kuliah:
[[98 88 78 90]
 [80 88 72 78]
 [90 92 88 86]]
